<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxr29yg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxr29yg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxr29yg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxr29yg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxr29yg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sxr29yg',
    'container.build_id' => 'e9014b5b',
    'container.build_time' => 1692628997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxr29yg');
